@ECHO OFF
ECHO Configuring environment variables for MySQL

SET MYSQL_BASEDIR=%~dp0
SET MYSQL_DATADIR=%MYSQL_BASEDIR%data
SET MYSQL_PORT=55555
SET MYSQL_USER=root
SET MYSQL_MODE=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

SET PATH=%MYSQL_BASEDIR%bin;%PATH%
